services:

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: appdb
      DEBEZIUM_PASSWORD: ${DEBEZIUM_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ./db/init:/docker-entrypoint-initdb.d

  zookeeper:
    image: debezium/zookeeper:2.7.3.Final

  kafka:
    image: debezium/kafka:2.7.3.Final
    depends_on:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181

  connect:
    image: debezium/connect:2.7.3.Final
    depends_on:
      - kafka
      - mysql
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses

  connect-register:
    image: curlimages/curl:8.10.1
    depends_on:
      - connect
    volumes:
      - ./debezium:/debezium
    environment:
      DEBEZIUM_PASSWORD: ${DEBEZIUM_PASSWORD}
    entrypoint: ["sh", "/debezium/register-connector.sh"]

  api:
    build: ./api
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: appdb

  client:
    build: ./client
    depends_on:
      - api
    ports:
      - "8080:80"

  consumer:
    build: ./consumer
    depends_on:
      - kafka
      - connect-register
    environment:
      KAFKA_BROKER: kafka:9092