#!/bin/sh

mysql -uroot -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
  CREATE USER IF NOT EXISTS 'debezium'@'%' IDENTIFIED BY '$DEBEZIUM_PASSWORD';
  GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT, LOCK TABLES ON *.* TO 'debezium'@'%';
  FLUSH PRIVILEGES;
EOSQL